// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3YI7IEikxQuJa2bj77aQXcYKNqZGGJY',
    appId: '1:798473537029:web:27009105c3e95bcf5cfe6c',
    messagingSenderId: '798473537029',
    projectId: 'ecom-app-e4f8a',
    authDomain: 'ecom-app-e4f8a.firebaseapp.com',
    storageBucket: 'ecom-app-e4f8a.firebasestorage.app',
    measurementId: 'G-VQZ6MTM47P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJSIuUPDmPgZoAYCKJIgQZhI151KK0WM',
    appId: '1:798473537029:android:cbcd3a2032a8a8975cfe6c',
    messagingSenderId: '798473537029',
    projectId: 'ecom-app-e4f8a',
    storageBucket: 'ecom-app-e4f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXa6naUz1XXmLBWkvVTDOgJBASZdWYRMo',
    appId: '1:798473537029:ios:d0fa6376c14d5e545cfe6c',
    messagingSenderId: '798473537029',
    projectId: 'ecom-app-e4f8a',
    storageBucket: 'ecom-app-e4f8a.firebasestorage.app',
    iosBundleId: 'com.example.ecomMcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXa6naUz1XXmLBWkvVTDOgJBASZdWYRMo',
    appId: '1:798473537029:ios:d0fa6376c14d5e545cfe6c',
    messagingSenderId: '798473537029',
    projectId: 'ecom-app-e4f8a',
    storageBucket: 'ecom-app-e4f8a.firebasestorage.app',
    iosBundleId: 'com.example.ecomMcp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw3YI7IEikxQuJa2bj77aQXcYKNqZGGJY',
    appId: '1:798473537029:web:7db4437441ec05d25cfe6c',
    messagingSenderId: '798473537029',
    projectId: 'ecom-app-e4f8a',
    authDomain: 'ecom-app-e4f8a.firebaseapp.com',
    storageBucket: 'ecom-app-e4f8a.firebasestorage.app',
    measurementId: 'G-LM2J2DCCC4',
  );

}