// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKnACSO-T6D9B8SlmmUZQLS0iOG5J338E',
    appId: '1:134457771826:web:a2d70d0b167c2ae6dbf92b',
    messagingSenderId: '134457771826',
    projectId: 'ecommerce-app-project-e10a4',
    authDomain: 'ecommerce-app-project-e10a4.firebaseapp.com',
    storageBucket: 'ecommerce-app-project-e10a4.firebasestorage.app',
    measurementId: 'G-7GHPG2HHSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHy2PnRT9CxP0hjCfIewtN13kdRtG9gQ',
    appId: '1:134457771826:android:4298711ac57a67b3dbf92b',
    messagingSenderId: '134457771826',
    projectId: 'ecommerce-app-project-e10a4',
    storageBucket: 'ecommerce-app-project-e10a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpAON5QtkbE6UOx-zplgtW3a4iWFwapY',
    appId: '1:134457771826:ios:2474f8dd840aca63dbf92b',
    messagingSenderId: '134457771826',
    projectId: 'ecommerce-app-project-e10a4',
    storageBucket: 'ecommerce-app-project-e10a4.firebasestorage.app',
    iosBundleId: 'com.example.ecomMcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpAON5QtkbE6UOx-zplgtW3a4iWFwapY',
    appId: '1:134457771826:ios:2474f8dd840aca63dbf92b',
    messagingSenderId: '134457771826',
    projectId: 'ecommerce-app-project-e10a4',
    storageBucket: 'ecommerce-app-project-e10a4.firebasestorage.app',
    iosBundleId: 'com.example.ecomMcp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKnACSO-T6D9B8SlmmUZQLS0iOG5J338E',
    appId: '1:134457771826:web:8dd1cd613b76a65fdbf92b',
    messagingSenderId: '134457771826',
    projectId: 'ecommerce-app-project-e10a4',
    authDomain: 'ecommerce-app-project-e10a4.firebaseapp.com',
    storageBucket: 'ecommerce-app-project-e10a4.firebasestorage.app',
    measurementId: 'G-RQ9QNWRFH5',
  );
}
